[build]
target = "x86_64-phanix.json"

# Enables us to use JSON target files
[unstable]
json-target-spec = true
# Rebuilds the 'core' library specifically for our hardware since the default is for Linux/Windows
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = true

[target.'cfg(target_os = "none")']
# This tells cargo run to package the kernel and launch QEMU
runner = "bootimage runner"

